title: Pranesh Kumar Narasimhan - Data Scientist Portfolio
description: Welcome to my data science portfolio!
logo: /images/pranesh-1.jpeg
show_downloads: true
theme: jekyll-theme-minimal  # Update with your chosen theme (e.g., minimal-mistakes, hydejack, etc.)

# Social media links
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/yourusername/
  - title: GitHub
    url: https://github.com/yourusername/
  # Add more social media links as needed

# Navigation links
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  # Add more navigation links as needed

# Other settings specific to your theme
# ...

# Optional additional settings
# ...
